# Generated by Django 5.2 on 2025-09-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todo',
            new_name='api_todo_owner_i_adcbad_idx',
            old_name='api_todo_owner_iscomp_idx',
        ),
    ]
